### ISSUE TITLE
Bypass the first 3 days

### ISSUE THREAD

**Issue by feildmaster** [propstg/plateup-overcooked-patience#10]
In plateup you are essentially protected from failure for the first 3 days. I am proposing that the first 3 days be ignored by this plugin to allow for quicker reset.

## Situation
Suppose you make a mistake early on (day 1-3), it doesn't happen often, which is why I never thought of this situation before. After being aware of the mistake I proceeded to let the customers fail so I could restart the day. Rather than disable the mod completely I opted to wait for my game to fail, due to that I was unable to quickly end the day as it was now wanting to buy new lives.

## Suggestion
1. Ignore the first 3 days, allowing the game to handle these days like usual.
2. Possibly make it optional - I say possibly because I can't see any reason why anyone would rather spend gold than reset the game as quickly as possible on the safe days.

**Comment by propstg** [comment]
This seems like a good idea, thanks! 

I do almost all of my testing on the first few days, so I would like to keep the current functionality to avoid having to play into day 4 to start testing changes, but I think I might be the only person that wants to lose money immediately. :)

I think I can make it work both ways with a compiler directive.

**Comment by propstg** [comment]
This was added in version 0.6.1, which has been released to the workshop. Thanks!
